# Generated by Django 2.1.5 on 2019-02-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finger',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15),
        ),
    ]
