# Generated by Django 2.1.5 on 2019-02-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0002_finger_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rf',
            name='rf',
        ),
        migrations.AddField(
            model_name='rf',
            name='down',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='rf',
            name='up',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15),
        ),
    ]
