# Generated by Django 2.1.5 on 2019-02-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_variable',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
