# Generated by Django 2.1.5 on 2019-02-17 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('settings', '0002_auto_20190207_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comand', models.CharField(max_length=10)),
                ('module', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('step', models.CharField(blank=True, max_length=10)),
                ('number', models.CharField(blank=True, default=' ', max_length=20)),
                ('up', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15)),
                ('down', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15)),
                ('print', models.TextField(blank=True, default=' ')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Contact')),
            ],
        ),
    ]
