# Generated by Django 2.1.5 on 2019-02-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
        ),
    ]
